name: Docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 📂
        uses: actions/checkout@v3

      - name: Set up Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: pip # Cache the pip dependencies

      - name: Install dependencies 🛠️
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt

      - name: Get the ChangeLog 📝
        run: |
          cp changelog.md docs/changelog.md

      - name: Get Version from VERSION file 🏷️
        id: get_version
        run: |
          VERSION=$(grep -m 1 'version = ' pyproject.toml | sed -E 's/.*version = "(.*)"/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: EConvert Jupyter notebooks to Markdown 📓➡️📄
        run: |
          jupyter nbconvert --to markdown --output-dir=docs/tutorials notebooks/*.ipynb

      - name: Build documentation 📄
        run: |
          mkdocs build

      - name: Deploy with Mike
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mike deploy --push --update-alias ${VERSION} --remote origin --branch gh-pages --force
          mike set-default --push ${VERSION} --remote origin --branch gh-pages --force
        env: # latest alias
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
